target-version = "py312"

# Same as Black.
line-length = 95
indent-width = 4

[lint]

preview = true

extend-select = [
    "UP",
    "TRY",
    "I",
    "SIM",
    "E",
    "PLR",
    "FAST",
    "C90",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D201",
    "D202",
    "D300",
    "D417",
    "D419",
    "DOC501",
    "ANN001",
    "ANN201",
    "ANN202",
    "ANN205",
    "B904",
]

ignore = [
    "PLR0402",
    "PLR0911",
    "PLR0913",
]

[lint.per-file-ignores]
"tests/**/*.py" = [
    "D100",   # Ignore missing docstrings for public modules
    "D103",   # Ignore missing docstrings for public functions
    "ANN001", # Ignore missing type annotation for methods
    "ANN201", # Ignore missing return type annotation for public function
    "ANN202", # Ignore missing return type annotation for private function
    "ANN205", # Ignore missing return type annotation for static function
    "PLR0914", # Ignore too many local variables
    "PLR0917" # Ignore too many positional arguments
]

[lint.pydocstyle]
# Use Google-style docstrings
convention = "google"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
