# Log Levels
DEBUG = "DEBUG"
INFO = "INFO"

# Core Modules
LOGGING_MAIN = "MAIN"
LOGGING_EXCEPTION = "EXCEPTION"
LOGGING_HTTP_ENCODE_SERVICE = "HTTP_ENCODE_SERVICE"

# Properties Management
LOGGING_PROPERTIES_MANAGER = "PROPERTIES_MANAGER"
LOGGING_PROPERTIES_MESSAGES_MANAGER = "PROPERTIES_MESSAGES_MANAGER"

# Database
LOGGING_DATABASE = "DATABASE"

# Middleware
LOGGIN_CHECK_AUTH_JWT_MIDDLEWARE = "CHECK_AUTH_JWT_MIDDLEWARE"

# Playlist
LOGGING_PLAYLIST_CONTROLLER = "PLAYLIST_CONTROLLER"
LOGGING_PLAYLIST_SERVICE = "PLAYLIST_SERVICE"
LOGGING_PLAYLIST_REPOSITORY = "PLAYLIST_REPOSITORY"

# Genre
LOGGING_GENRE_SERVICE = "GENRE_SERVICE"
LOGGING_GENRE_CLASS = "GENRE_CLASS"
LOGGING_GENRE_CONTROLLER = "GENRE_CONTROLLER"

# Song
LOGGING_SONG_SERVICE_PROVIDER = "SONG_SERVICE_PROVIDER"
LOGGING_BASE_SONG_SERVICE = "BASE_SONG_SERVICE"
LOGGING_BASE_SONG_REPOSITORY = "BASE_SONG_REPOSITORY"

LOGGING_SONG_AWS_SERVERLESS_FUNCTION_REPOSITORY = (
    "SONG_AWS_SERVERLESS_FUNCTION_REPOSITORY"
)
LOGGING_SONG_AWS_SERVERLESS_FUNCTION_SERVICE = "SONG_AWS_SERVERLESS_FUNCTION_SERVICE"
LOGGING_SONG_AWS_SERVERLESS_FUNCTION_SERVICE_VALIDATIONS = (
    "SONG_AWS_SERVERLESS_FUNCTION_SERVICE_VALIDATIONS"
)

LOGGING_SONG_BLOB_REPOSITORY = "SONG_BLOB_REPOSITORY"
LOGGING_SONG_BLOB_SERVICE = "SONG_BLOB_SERVICE"
LOGGING_SONG_BLOB_SERVICE_VALIDATIONS = "SONG_BLOB_SERVICE_VALIDATIONS"


# Security
LOGGING_SECURITY_SERVICE = "SECURITY_SERVICE"

# Search
LOGGING_SEARCH_SERVICE = "SEARCH_SERVICE"
LOGGING_SEARCH_CONTROLLER = "SEARCH_CONTROLLER"

# Base user
LOGGING_BASE_USERS_SERVICE = "BASE_USER_SERVICE"
LOGGING_BASE_USERS_REPOSITORY = "BASE_USER_REPOSITORY"
LOGGING_USER_SERVICE_PROVIDER = "USER_SERVICE_PROVIDER"
LOGGING_USER_COLLECTION_PROVIDER = "USER_COLLECTION_PROVIDER"

# User
LOGGING_USER_REPOSITORY = "USER_REPOSITORY"
LOGGING_USER_SERVICE = "USER_SERVICE"

# Artist
LOGGING_ARTIST_REPOSITORY = "ARTIST_REPOSITORY"
LOGGING_ARTIST_SERVICE = "ARTIST_SERVICE"

# Utilities
LOGGING_AUDIO_MANAGEMENT_UTILS = "AUDIO_MANAGEMENT_UTILS"
