LOGGING_MAIN = "MAIN"
LOGGING_PROPERTIES_MANAGER = "PROPERTIES_MANAGER"
LOGGING_DATABASE = "DATABASE"
LOGGING_EXCEPTION = "EXCEPTION"
LOGGIN_CHECK_AUTH_JWT_MIDDLEWARE = "CHECK_AUTH_JWT_MIDDLEWARE"


DEBUG = "DEBUG"
INFO = "INFO"
