LOGGING_MAIN = "MAIN"
LOGGING_PROPERTIES_MANAGER = "PROPERTIES_MANAGER"
LOGGING_DATABASE = "DATABASE"
LOGGING_EXCEPTION = "EXCEPTION"
LOGGIN_CHECK_AUTH_JWT_MIDDLEWARE = "CHECK_AUTH_JWT_MIDDLEWARE"
LOGGING_HTTP_ENCODE_SERVICE = "HTTP_ENCODE_SERVICE"
LOGGING_PLAYLISTS_ROUTER = "PLAYLISTS_ROUTER"
LOGGING_PLAYLISTS_SERVICE = "PLAYLISTS_SERVICE"
LOGGING_PLAYLISTS_REPOSITORY = "PLAYLISTS_REPOSITORY"
LOGGING_SONG_SERVICE_PROVIDER = "SONG_SERVICE_PROVIDER"


DEBUG = "DEBUG"
INFO = "INFO"
