"""Constants for AWS Lambda function"""

# ENV PATHS
BUCKET_NAME_ENV_PATH = "BUCKET_NAME"
DISTRIBUTION_ID_ENV_PATH = "DISTRIBUTION_ID"

# AWS

S3 = "s3"
CLOUDFRONT = "cloudfront"
CLOUDFRONT_DISTRIBUTION = "Distribution"
CLOUDFRONT_DISTRIBUTION_DOMAIN_NAME = "DomainName"

# SPOTIFY ELECTRON

BUCKET_BASE_PATH = "canciones/"
