name: Enforce Branch Naming

on:
  create:
    branches:
      - "*"

jobs:
  enforce-branch-naming:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check branch name format
        id: check_branch
        run: |
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          if [[ ! "$branch_name" =~ (^(feat|fix|refactor|docs|chore|test|style|build|ci|perf|revert)\/.*)|(master\-.*)|(dependabot\-.*) ]]; then
            echo "Branch name doesn't match the required format."
            exit 1
          fi
