name: Generate and save documentation of API

on:
  pull_request:
    types: [closed]

jobs:
  generate-and-save-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.PAT }}

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies and generate docs
        working-directory: Backend/
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python generate-docs.py
        env:
            MONGO_URI : ${{ secrets.MONGO_URI }}
            SERVERLESS_FUNCTION_URL : none
            ARCH : BLOB
            ENV_VALUE : TEST

      - name: Add and commit changes
        working-directory: Backend/
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add api-docs-spotify-electron.html
          if git commit -m "docs : Update API documentation"; then
            echo "CHANGES=true" >> $GITHUB_ENV
          else
            echo "No changes to commit"
            echo "CHANGES=false" >> $GITHUB_ENV
          fi

      - name: Check if there are changes to push
        id: check_changes
        run: |
          if [ "$CHANGES" == "true" ]; then
            echo "Changes detected"
          else
            echo "No changes detected"
          fi

      - name: Pushing to the protected branch 'master'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PAT }}
          branch: ${{ github.base_ref }}
