ARCH_STREAMING_LAMBDA = "STREAMING_LAMBDA"
ARCH_STREAMING_SDK = "STREAMING_SDK"
ARCH_DB_BLOB = "DB_BLOB"

PROD = "PROD"
TEST = "TEST"

ARCHITECTURE_ENV_NAME = "ARCH"
DEFAULT_ARCHITECTURE = ARCH_STREAMING_LAMBDA

SECRET_KEY_SIGN_ENV_NAME = "SECRET_KEY_SIGN"
MONGO_URI_ENV_NAME = "MONGO_URI"
DISTRIBUTION_ID_ENV_NAME = "DISTRIBUTION_ID"
LAMBDA_URL_ENV_NAME = "LAMBDA_URL"
ENV_VALUE_ENV_NAME = "ENV_VALUE"
