name: Backend Tests

on:
  pull_request:
    branches:
      - 'master'
      - 'master-*'
jobs:

  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: Install dependencies
        working-directory: Backend
        run: pip install -r requirements.txt && pip install -r requirements-test.txt

      - name: Run tests Streaming lambda Architecture
        working-directory: Backend/
        run: python -m pytest tests/
        env:
          MONGO_URI : ${{ secrets.MONGO_URI }}
          SECRET_KEY_SIGN : ${{ secrets.SECRET_KEY_SIGN }}
          DISTRIBUTION_ID : ${{ secrets.DISTRIBUTION_ID }}
          LAMBDA_URL : ${{ secrets.LAMBDA_URL }}
          ARCH : "STREAMING_LAMBDA"
          ENV_VALUE : "PROD"

      - name: Run tests Database Blob Architecture
        working-directory: Backend/
        run: python -m pytest .
        env:
          MONGO_URI : ${{ secrets.MONGO_URI }}
          SECRET_KEY_SIGN : ${{ secrets.SECRET_KEY_SIGN }}
          DISTRIBUTION_ID : ${{ secrets.DISTRIBUTION_ID }}
          LAMBDA_URL : ${{ secrets.LAMBDA_URL }}
          ARCH : "DB_BLOB"
          ENV_VALUE : "PROD"

      - name: Fail workflow on test failure
        if: ${{ failure() }}
        run: exit 1
