name: Deploy Github pages with updated MkDocs on https://github.com/AntonioMrtz/SpotifyElectron_Web

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  trigger-action:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # Check if PR was merged
    steps:
      - name: Trigger SpotifyElectron website Github pages deploy workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.Deploy_SpotifyElectron_Web_gh_pages }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/AntonioMrtz/SpotifyElectron/dispatches \
            -d '{"event_type":"deploy-with-mkdocs","client_payload":{"unit":false,"integration":true}}'
