name: Deploy Github pages with updated MkDocs on Landing page

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: read
  repository_dispatch: write

jobs:
  trigger-action:
    runs-on: ubuntu-latest
    if: |
      (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master') ||
      github.event_name == 'workflow_dispatch'
    steps:
      - name: Trigger SpotifyElectron website Github pages deploy workflow
        run: |
          curl -v -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.Deploy_SpotifyElectron_Web_gh_pages }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/AntonioMrtz/SpotifyElectron_Web/dispatches \
            -d '{"event_type":"deploy-with-mkdocs","client_payload":{"unit":false,"integration":true}}'
