name: Pre-commit Checks
on:
  push:
    branches: [master-*]
  pull_request:    

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run specified hooks
        run: |
          pre-commit run \
            check-yaml \
            check-json \
            end-of-file-fixer \
            trailing-whitespace \
            check-merge-conflict \
            --all-files
