name: Check Ruff lint
on:
  pull_request:
    branches:
      - "master"
      - "master-*"
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
