name: Ruff lint check

on:
  pull_request:

permissions:
  contents: read

jobs:
  ruff-lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Run ruff lint check
        uses: astral-sh/ruff-action@v3
        with:
          version: "0.11.5"
          src: "./Backend"
          args: "check --fix"
